### ISSUE TITLE
API research

### ISSUE THREAD

**Issue by Matt-STJR** [M-Seross/Covid-101App#1]
- [x] API for pulling articles
- [x] API for pulling global Covid-19 stats

**Comment by goggles320** [comment]
COVID-19 tracker API - refer to website.
https://documenter.getpostman.com/view/2568274/SzS8rjbe?version=latest
Actual API: https://covidapi.info/api/v1/country/AUS

**Comment by goggles320** [comment]
API for global count: https://covidapi.info/api/v1/global
